In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

# Q1:  Why  the result is " array([56.]) "?

In [16]:
x = np.random.random(56)*100
x[x<87]

array([85.85173664, 21.36177004, 25.78563931, 54.30625153, 33.77706435,
       70.87620826, 30.97703495, 39.99995418, 70.70194015, 75.01080351,
       66.46557635, 46.75320757, 22.79664327, 45.22052184, 45.3752863 ,
       21.28778564, 31.9705782 , 82.6446028 ,  3.13579227, 41.27692493,
       51.27880673, 13.76518033, 84.36457136, 30.65646802,  0.81541807,
       76.45335254, 20.19153256, 46.5686447 ,  0.2689127 , 67.87982126,
       79.9019337 , 10.48377813, 47.04956814, 64.43765447, 60.39410444,
       46.44159757, 52.29640759, 30.04821599, 35.30168524, 85.36131406,
       21.17752057, 50.05244824,  0.60863919, 31.2549532 , 60.79930561,
       76.88035207, 66.77993867, 56.44682929,  3.98444529, 61.90857511,
       13.8426172 ])

In [11]:
x

array([  56.        ,  168.44897959,  280.89795918,  393.34693878,
        505.79591837,  618.24489796,  730.69387755,  843.14285714,
        955.59183673, 1068.04081633, 1180.48979592, 1292.93877551,
       1405.3877551 , 1517.83673469, 1630.28571429, 1742.73469388,
       1855.18367347, 1967.63265306, 2080.08163265, 2192.53061224,
       2304.97959184, 2417.42857143, 2529.87755102, 2642.32653061,
       2754.7755102 , 2867.2244898 , 2979.67346939, 3092.12244898,
       3204.57142857, 3317.02040816, 3429.46938776, 3541.91836735,
       3654.36734694, 3766.81632653, 3879.26530612, 3991.71428571,
       4104.16326531, 4216.6122449 , 4329.06122449, 4441.51020408,
       4553.95918367, 4666.40816327, 4778.85714286, 4891.30612245,
       5003.75510204, 5116.20408163, 5228.65306122, 5341.10204082,
       5453.55102041, 5566.        ])

In [9]:
l=[3,6,75,27]
l=np.array(l)
l[3]

27

In [3]:
x[x>87]

array([ 168.44897959,  280.89795918,  393.34693878,  505.79591837,
        618.24489796,  730.69387755,  843.14285714,  955.59183673,
       1068.04081633, 1180.48979592, 1292.93877551, 1405.3877551 ,
       1517.83673469, 1630.28571429, 1742.73469388, 1855.18367347,
       1967.63265306, 2080.08163265, 2192.53061224, 2304.97959184,
       2417.42857143, 2529.87755102, 2642.32653061, 2754.7755102 ,
       2867.2244898 , 2979.67346939, 3092.12244898, 3204.57142857,
       3317.02040816, 3429.46938776, 3541.91836735, 3654.36734694,
       3766.81632653, 3879.26530612, 3991.71428571, 4104.16326531,
       4216.6122449 , 4329.06122449, 4441.51020408, 4553.95918367,
       4666.40816327, 4778.85714286, 4891.30612245, 5003.75510204,
       5116.20408163, 5228.65306122, 5341.10204082, 5453.55102041,
       5566.        ])